4. web/web_project5/posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"
urlpatterns = [
    path("feeds/", views.feeds, name="feeds"),
    path("comment_add/", views.comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", views.comment_delete, name="comment_delete"),
    path("post_add/", views.post_add, name="post_add"),
    path("tags/<str:tag_name>/", views.tags, name="tags"), 
    path("<int:post_id>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/like/", views.post_like, name="post_like"),
]

4. web/web_project5/pystagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from pystagram import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
]
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

4. web/web_project5/users/urls.py
from django.urls import path
from users import views

app_name = "users"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"), 
    path("signup/", views.signup, name="signup"),
    path("<int:user_id>/profile/", views.profile, name="profile"),
    path("<int:user_id>/followers/", views.followers, name="followers"),
    path("<int:user_id>/following/", views.following, name="following"),
    path("<int:user_id>/follow/", views.follow, name="follow"),
]

4. web/web_project5/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey("users.User", 
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    content = models.TextField("내용", blank=True)           # 얘만 내가 고르는거임
    created = models.DateTimeField("작성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)    # 그냥 HashTag 하면 인식 안 됨 밑에 있어서 그래서 posts.HashTag
    
    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"

class PostImage(models.Model):
    post = models.ForeignKey(Post,
                             verbose_name="포스트",
                             on_delete=models.CASCADE)
    photo = models.ImageField("사진", upload_to="post")

class Comment(models.Model):
    user = models.ForeignKey("users.User",
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    post = models.ForeignKey(Post,
                             verbose_name="포스트",
                             on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add=True)

class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

4. web/web_project5/posts/forms.py
from django import forms
from posts.models import Comment, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "댓글 달기...",
                }
            )
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "content",
        ]

4. web/web_project5/posts/views.py
from django.shortcuts import render, redirect
from posts.models import Post, Comment, PostImage, HashTag
from posts.forms import CommentForm, PostForm
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse

# Create your views here.
def feeds(request):
    # 요청에 포함된 사용자가 로그인하지 않은 경우
    if not request.user.is_authenticated:
        # /users/login/ URL로 이동시킴
        return redirect("users:login")

    # 모든 글 목록을 템플릿으로 전달
    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {"posts": posts, "comment_form":comment_form}
    return render(request, "posts/feeds.html", context)


@require_POST # 댓글 작성을 처리할 View, Post 요청만 허용
def comment_add(request):
    # request.POST 로 전달된 데이터를 사용해 CommentForm 인스턴스를 생성
    form = CommentForm(data=request.POST)

    if form.is_valid():
        # commit=False 옵션으로 메모리상에 Comment 객체 생성
        comment = form.save(commit=False)

        # Comment 생성에 필요한 사용자정보를 request에서 가져와 할당
        comment.user = request.user

        # DB에 Comment 객체 저장
        comment.save()

        # URL 로 "next"값을 전달받았다면 댓글 작성 완료 후 전달 받은 값으로 이동
        if request.GET.get("next"):
            url_next = request.GET.get("next")

        else: # "next"값을 전달받지 않았다면 피드페이지의 글 위치로 이동
            # 생성한 comment에서 연결된 post 정보를 가져와서 id값을 사용
            url_next = reverse("posts:feeds") + f"#post-{comment.post.id}"
        return HttpResponseRedirect(url_next)
    

@require_POST
def comment_delete(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if comment.user == request.user:
        comment.delete()
        url = reverse("posts:feeds") + f"#post-{comment.post.id}"
        return HttpResponseRedirect(url)
    else:
        return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다")
    
def post_add(request):
    if request.method == "POST":
        # request.POST로 온 데이터("content")는 PostForm으로 처리
        form = PostForm(request.POST)

        if form.is_valid():
            # Post의 "user" 값은 request에서 가져와 자동할당한다
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            # Post를 생성한 후
            # request.FILES.getlist("images")로 전송된 이미지들을 순회하며 
            # PostImage 객체를 생성
            for image_file in request.FILES.getlist("images"):
                # request.FILES 또는 request.FILES.getlist()로 가져온 파일은
                # MOdel의 ImageField 부분에 곧바로 할당
                PostImage.objects.create(
                    post=post,
                    photo=image_file,
                )

            # "tags"에 전달된 문자열을 분리해 HashTag생성
            tag_string = request.POST.get("tags")
            if tag_string:
                tag_name_list = [tag_name.strip() for tag_name in tag_string.split(",")]
                for tag_name in tag_name_list:
                    tag, _ = HashTag.objects.get_or_create(
                        name=tag_name,
                    )
                    # get_or_create로 생성하거나 가져온 HashTag객체를 Post의 tags에 추가
                    post.tags.add(tag)

            # 모든 PostImage와 Post의 생성이 완료되면
            # 피드페이지로 이동하여 생성된 Post의 위치로 스크롤되도록 함
            url = reverse("posts:feeds") + f"#post-{post.id}"
            return HttpResponseRedirect(url)
            
    else:
        form = PostForm()
    
    context = {"form": form}
    return render(request, "posts/post_add.html", context)

def tags(request, tag_name):
    try:
        tag = HashTag.objects.get(name=tag_name)
    except HashTag.DoesNotExist:
        # tag_name에 해당하는 HashTag를 찾지 못한 경우 빈 QuerySet을 반환
        posts = Post.objects.none()
    else:
        # tags(M2M 필드)에 찾은 HashTag 객체가 있는 Post 들을 필터
        posts = Post.objects.filter(tags=tag)

    # context로 Template에 필터링 된 Post QuerySet을 넘겨주며
    # 어떤 tag_name으로 검색했는지도 넘겨줌
    context = {
        "tag_name": tag_name,
        "posts":posts,
    }
    return render(request, "posts/tags.html", context)

def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = CommentForm()
    context = {
        "post":post,
        "comment_form":comment_form,
    }
    return render(request, "posts/post_detail.html", context)

# URL 에서 좋아요 처리할 Post의 id를 전달받는다
def post_like(request, post_id):
    post = Post.objects.get(id=post_id)
    user = request.user

    # 사용자가 "좋아요를 누른 Post목록"에 "좋아요 버튼을 누른 Post"가 존재한다면
    if user.like_posts.filter(id=post.id).exists():
        # 좋아요 목록에서 삭제
        user.like_posts.remove(post)

    # 존재하지 않는다면 좋아요 목록에 추가
    else:
        user.like_posts.add(post)

    # next로 값이 전달되었다면 해당 위치로, 전달되지 않았다면 피드페이지에서 해당 Post위치로 이동
    url_next = request.GET.get("next") or reverse("posts:feeds") + f"#post-{post.id}"
    return HttpResponseRedirect(url_next)

4. web/web_project5/templates/posts/feeds.html
{% extends 'base_slider.html' %}

{% block content %}
<div id="feeds" class="post-container">
    <!-- 전달된 Post QuerySet 객체를 순회 -->
    {% for post in posts %}
        {% with post.id|stringformat:"s" as post_id %}
            {% url 'posts:feeds' as action_redirect_to %}
            {% include 'posts/post.html' with action_redirect_url=action_redirect_to|add:'#post-'|add:post_id %}
        {% endwith %}
    {% endfor %}
</div>
{% endblock %}

4. web/web_project5/templates/posts/post.html
<article class="post" id="post-{{ post.id }}">
    <header class="post-header">
        <a href="{% url 'users:profile' user_id=post.user.id %}">
            {% if post.user.profile_image %}
                <img src="{{ post.user.profile_image.url }}">
            {% endif %}
            <span>{{ post.user.username }}</span>
        </a>
        <!-- 글의 작성자가 로그인 한 사용자라면 팔로우 버튼을 표시하지 않는다 -->
        <!-- (자기 자신을 팔로우 하는 것을 방지) -->
        {% if user != post.user %}
            <form action="{% url 'users:follow' user_id=post.user.id %}?next={{ action_redirect_url }}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-primany">
                    <!-- 이 Post의 작성자가 이미 자신의 팔로잉 목록에 포함된 경우 -->
                    {% if post.user in user.following.all %}
                        Unfollow
                    <!-- 이 Post의 작성자를 아직 팔로잉하지 않은 경우 -->
                    {% else %}
                        Follow
                    {% endif %}
                </button>
            </form>
        {% endif %}
    </header>
    <!-- 이미지 슬라이드 영역 -->
    <div class="post-images splide">
        <div class="splide__track">
            <ul class="splide__list">
                {% for image in post.postimage_set.all %}
                    {% if image.photo %}
                        <li class="splide__slide">
                            <img src="{{ image.photo.url }}">
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="post-content">
        {{ post.content|linebreaksbr }}
        <div class="post-tags">
            {% for tag in post.tags.all %}
                <span>
                    <a href="{% url 'posts:tags' tag_name=tag.name %}">#{{ tag.name }}</a>
                </span>
            {% endfor %}
        </div>
    </div>
    <div class="post-buttons">
        <form action="{% url 'posts:post_like' post_id=post.id %}?next={{ action_redirect_url }}" method="POST">
            {% csrf_token %}
            <button type="submit"
            {% if user in post.like_users.all %}
                style="color: #0A6ECD;"
            {% endif %}>
            <!-- Post related_name으로 지정한 like_users로 좋아요를 누른 사용자 수를 가져옴 -->
                Likes({{ post.like_users.count }})
            </button>
        </form>
        <span>Comments({{ post.comment_set.count }})</span>
    </div>
    <div class="post-comments">
        <ul>
            <!-- 각 Post에 연결된 PostComment 들을 순회 -->
            {% for comment in post.comment_set.all %}
                <li>
                    <span>{{ comment.user.username }}</span>
                    <span>{{ comment.content }}</span>

                    <!-- 댓글 삭제 Form 추가 -->
                    {% if user == comment.user %}
                        <form method="POST" action="{% url 'posts:comment_delete' comment_id=comment.id %}">
                            {% csrf_token %}
                            <button type="submit">삭제</button>
                        </form>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
    <small>{{ post.created }}</small>
    <div class="post-comment-create">
        <!-- action 속성을 "댓글추가" View를 가리키는 URL로 지정 -->
        <form method="POST" action="{% url 'posts:comment_add' %}?next={{ action_redirect_url }}">
            {% csrf_token %}
            <!-- 사용자가 직접 입력하지 않는 고정된 데이터를 form내부에 위치 -->
            <input type="hidden" name="post" value="{{ post.id }}">
            <!-- 전달된 CommentForm의 필드들 중, "content"필드만 렌더링 -->
            {{ comment_form.content }}
            <button type="submit">게시</button>
        </form>
    </div>
</article>

4. web/web_project5/templates/posts/post_add.html
{% extends 'base_nav.html' %}

{% block content %}
    <div id="post-add">
        <h1>Post-add</h1>
        <!-- file을 전송할 것이므로 enctype을 수정해야함 -->
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div>
                <lable for="id_images">이미지</lable>
                <input id="id_images" name="images" type="file" multiple>
            </div>
            {{ form.as_p }}
            <div>
                <label for="id_tags">해시태그</label>
                <input id="id_tags" name="tags" type="text" placeholder="쉼표(,)로 구분하여 여러 태그 입력">
            </div>
            <button type="submit">게시</button>
        </form> 
        <!-- 사용자들이 다시 우리에게 전달할 수 있게 사용하는 것이 form -->
        <!-- POST = 데이터를 쌓아주세요, 데이터를 수정해 주세요~ 의 약속 -->
        <!-- POST 가 나오면 따라서 {% csrf_token %}이 나온당 -->
        <!-- form이란 데이터를 받을게 > 중괄호 사용 > as_p = p라는 태그로 받을게 -->
    </div>
{% endblock %}

4. web/web_project5/templates/posts/post_detail.html
{% extends 'base_slider.html' %}

{% block content %}
<div id="feeds" class="post-container">
    {% url 'posts:post_detail' post.id as action_redirect_to %}
    <!--  action_redirect_to 라는 변수에 담았음 -->
    {% include 'posts/post.html' with action_redirect_url=action_redirect_to %}
</div>
{% endblock %}

4. web/web_project5/templates/posts/tags.html
{% extends 'base_nav.html' %}

{% block content %}
<div id="tags">
    <header class="tags-header">
        <h2>{{ tag_name }}</h2>
        <div>게시물 {{ posts.count }}</div>s
    </header>
    <div class="post-grid-container">
        {% for post in posts %}
            <!-- Post에 연결된 PostImage가 있으며, 연결된 첫 번째 PostImage의 -->
            <!-- photo가 비어있지 않은 경우 -->
            {% if post.postimage_set.first and post.postimage_set.first.photo %}
                <div class="post-grid">
                    <a href="{% url 'posts:post_detail' post_id=post.id %}">
                        <img src="{{ post.postimage_set.first.photo.url }}" alt="">
                    </a>
                </div>
            {% endif %}
        {% empty %}
            <p>검색된 게시물이 없습니다</p>
        {% endfor %}
    </div>
</div>

{% endblock %}