Portfolio/1st_mini_project/cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'

urlpatterns = [
    path('', views.index, name='index'),
    path('main/', views.CalendarView.as_view(), name='calendar'),
    path("detail/", views.post_detail, name="post_detail"),
    path('save_event/', views.save_event, name='save_event'),
]

Portfolio/1st_mini_project/diary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from diary import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index),
    path("cal/", include("cal.urls")),
    path("users/", include("users.urls")),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

Portfolio/1st_mini_project/users/urls.py
from django.urls import path
from users import views
from django.contrib.auth.views import LogoutView

app_name = "users"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("login2/", views.login_view2, name="login2"),
    path("login3/", views.login_view3, name="login3"),
    path('logout/', views.logout_view, name='logout'),
    path("signup/", views.signup, name="signup"),
]

Portfolio/1st_mini_project/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    profile_image = models.ImageField("프로필 이미지", upload_to="users.profile", blank=True)
    short_description = models.TextField("소개글", blank=True)
    
    def __str__(self):
        return self.username

Portfolio/1st_mini_project/users/forms.py
from django import forms
from users.models import User
from django.core.exceptions import ValidationError

class LoginForm(forms.Form):
    username = forms.CharField(
        min_length=4,
        widget=forms.TextInput(
            attrs={"placeholder": "사용자명 (4자리 이상)"},
        )
    )
    password = forms.CharField(
        min_length=4,
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호 (4자리 이상)"},
        )    
    )

class SignupForm(forms.Form):
    username = forms.CharField(
        min_length=4,
        widget=forms.TextInput(
            attrs={"placeholder": "사용자명 (4자리 이상)"},
        )
    )
    password1 = forms.CharField(
        min_length=4,
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호 (4자리 이상)"},
        )    
    )

    password2 = forms.CharField(
        min_length=4,
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호 확인"},
        )    
    )

    def clean_username(self):
        username = self.cleaned_data["username"]

        if User.objects.filter(username=username).exists():
            raise ValidationError(f"입력한 사용자명({username})은 이미 사용 중입니다")
        
        return username
    
    def clean(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if password1 != password2:
            # password2 필드에 오류를 추가
            self.add_error("password2",
                           "비밀번호와 비밀번호 확인란의 값이 다릅니다")
            
    def save(self):
        username = self.cleaned_data["username"]
        password1 = self.cleaned_data["password1"]

        user = User.objects.create_user(
            username=username,
            password=password1,
        )
        return user

Portfolio/1st_mini_project/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from users.forms import LoginForm, SignupForm
from django.contrib.auth import authenticate, login, logout
from users.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def login_view(request):
        # LoginForm 인스턴스를 생성
        form = LoginForm()
        form2 = SignupForm()
        context = {"form":form, "form2":form2}
        return render(request, "users/login.html", context)

def login_view2(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            # username과 password 값을 가져와 변수에 할당
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            # username, password 에 해당하는 사용자가 있는지 검사
            user = authenticate(username=username, password=password)

            # 해당 사용자가 존재한다면
            if user:
                # 로그인 처리 후, 피드페이지로 redirect
                login(request, user)
                return redirect("/cal")
        form2 = SignupForm
        # 실패한 경우 다시 LoginForm 을 사용한 로그 페이지 렌더링
        context = {"form" : form, "form2" : form2}

    else:
        # LoginForm 인스턴스를 생성
        form = LoginForm()

        # 생성한 LoginForm 인스턴스를 템플릿에 "form" 이라는 키로 전달
        context = {
            "form" : form,
            "form2" : form2,
        }
    return render(request, "users/login.html", context)



def login_view3(request):
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            # username과 password 값을 가져와 변수에 할당
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            # username, password 에 해당하는 사용자가 있는지 검사
            user = authenticate(username=username, password=password)

            # 해당 사용자가 존재한다면
            if user:
                # 로그인 처리 후, 피드페이지로 redirect
                login(request, user)
                return render("cal.calendar.html")
        # 실패한 경우 다시 LoginForm 을 사용한 로그 페이지 렌더링
        context = {"form" : form,}

    else:
        # LoginForm 인스턴스를 생성
        form = LoginForm()

        # 생성한 LoginForm 인스턴스를 템플릿에 "form" 이라는 키로 전달
        context = {
            "form" : form,
        }
        return redirect("/cal", context)

def logout_view(request):
    # logout 함수 호출에 request를 전달
    logout(request)

    # logout 처리 후, 캘린더 페이지로 이동
    return redirect("/cal")

def signup(request):
    if request.method == "POST":
        form = SignupForm(data=request.POST)
        # Form에 에러가 없다면 form의 save() 메서드로 사용자를 생성
        if form.is_valid():
            user = form.save()
            login(request, user)
            return render(request, "users/login.html")
    
    # GET 요청에서는 빈 Form을 보여줌
    else:
    # SignupForm 인스턴스를 생성, Template에 전달
        form = SignupForm()
    
    # context로 전달되는 form 은 두 가지 경우가 존재
    # 1. POST 요청에서 생성된 form이 유효하지 않은 경우
        # -> 에러를 포함한 form이 사용자에게 보여짐
    # 2. GET 요청으로 빈 form이 생성되는 경우
        # -> 빈 form이 사용자에게 보여짐
    return render(request, "users/login.html")


Portfolio/1st_mini_project/templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <link rel="stylesheet" href="{% static 'css/login.css' %}">
        <title>Schedule Helper</title>
        <nav class="navbar bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand"><h2>Schedule Helper</h2></a>
            </div>
        </nav>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,800">
    </head>

    <body>
        <div class="container" id="container">
            <div class="form-container sign-up-container">
                <form action="#">
                    {% csrf_token %}
                    <h1>회원가입</h1>
                    <span>이메일을 사용하여 회원가입 하기</span>
                    {% for i in form2 %}
                    {{ i }}
                    {% endfor %}
                    <button type="submit">회원가입</button>
                </form>
            </div>
            <div class="form-container sign-in-container">
                <form action="{% url 'users:login2' %}" method="POST" id="login" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1>로그인</h1>
                    <span>계정을 사용하여 로그인</span>
                    {% for i in form %}
                    {{ i }}
                    {% endfor %}
                    <button type="submit">로그인</button>
                </form>
            </div>
            <div class="overlay-container">
                <div class="overlay">
                    <div class="overlay-panel overlay-left">
                        <h1>환영해요!</h1>
                        <p>Helper와 일정 여행을 떠나볼까요?</p>
                        <button class="ghost" id="signIn">로그인</button>
                    </div>
                    <div class="overlay-panel overlay-right">
                        <h1>Helper와 함께 하루를 시작해 보세요!</h1>
                        <p>회원가입을 통해 Schedule Helper를 누려보세요!</p>
                        <button class="ghost" id="signUp" href="{url 'users':'signup}">회원가입</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- JavaScript 코드 추가 -->
        <script src="{% static 'js/login.js' %}"></script>
    </body>
</html>