Portfolio/1st_mini_project/cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'

urlpatterns = [
    path('', views.index, name='index'),
    path('main/', views.CalendarView.as_view(), name='calendar'),
    path("detail/", views.post_detail, name="post_detail"),
    path('save_event/', views.save_event, name='save_event'),
]

Portfolio/1st_mini_project/diary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from diary import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index),
    path("cal/", include("cal.urls")),
    path("users/", include("users.urls")),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

Portfolio/1st_mini_project/users/urls.py
from django.urls import path
from users import views
from django.contrib.auth.views import LogoutView

app_name = "users"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("login2/", views.login_view2, name="login2"),
    path("login3/", views.login_view3, name="login3"),
    path('logout/', views.logout_view, name='logout'),
    path("signup/", views.signup, name="signup"),
]

Portfolio/1st_mini_project/cal/models.py
from django.db import models

# Create your models here.
class class_contents(models.Model):
    keyword = models.CharField(max_length=200)
    content = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

class Area(models.Model):
    ID = models.SmallIntegerField(null=False, primary_key=True)
    Area = models.CharField(max_length=6)
    Area_detail = models.CharField(max_length=5)
    address_code = models.CharField(max_length=10)
    Weather_forecast_code = models.CharField(max_length=8)
    Temperature_code = models.CharField(max_length=8)
    X = models.DecimalField(max_digits=10, decimal_places=6)
    Y = models.DecimalField(max_digits=10, decimal_places=6)
    
class Temperature(models.Model):
    ID = models.SmallIntegerField(null=False, primary_key=True)
    Date = models.CharField(max_length=8)
    regId = models.CharField(max_length=8)
    taMin3 = models.SmallIntegerField()
    taMax3 = models.SmallIntegerField()
    taMin4 = models.SmallIntegerField()
    taMax4 = models.SmallIntegerField()
    taMin5 = models.SmallIntegerField()
    taMax5 = models.SmallIntegerField()
    taMin6 = models.SmallIntegerField()
    taMax6 = models.SmallIntegerField()
    taMin7 = models.SmallIntegerField()
    taMax7 = models.SmallIntegerField()
    taMin8 = models.SmallIntegerField()
    taMax8 = models.SmallIntegerField()
    taMin9 = models.SmallIntegerField()
    taMax9 = models.SmallIntegerField()
    taMin10 = models.SmallIntegerField()
    taMax10 = models.SmallIntegerField()


class EventModel(models.Model):
    ename = models.CharField(max_length=100)  # 이벤트 이름 필드
    edate_s = models.CharField(max_length=10)
    edate_e = models.CharField(max_length=10)
    edesc = models.TextField()# 이벤트 설명 필드
    user_id = models.CharField(max_length=20)
    def __str__(self):
        return self.ename

class today_weather(models.Model):
    Date = models.CharField(max_length=8)
    information = models.CharField(max_length=10)
    value = models.FloatField()


class Restaurant(models.Model):
    rank = models.CharField(max_length=1, unique=False)
    information = models.CharField(max_length=2)
    title = models.CharField(max_length=20)
    address = models.CharField(max_length=50)

class Travel(models.Model):
    rank = models.CharField(max_length=1, unique=False)
    title = models.CharField(max_length=20)
    address = models.CharField(max_length=50)


Portfolio/1st_mini_project/cal/forms.py
from django import forms
from .models import EventModel  # 이벤트 모델 임포트



class EventForm(forms.ModelForm):
    class Meta:
        model=EventModel  # 사용할 이벤트 모델 지정
        fields = ['ename', 'edate_s', 'edate_e', 'edesc']

Portfolio/1st_mini_project/cal/views.py
from django.shortcuts import render, redirect
from datetime import datetime, timedelta, date
from django.views import generic
from django.utils.safestring import mark_safe
import calendar
from django.contrib.auth import authenticate, login, logout
from django.utils import timezone

from cal.forms import EventForm
from users.forms import *
from .models import *
from .utils import Calendar

# Create your views here.

# generic.ListView 클래스를 상속받아, class_contents 모델을 이용하여 DB에서 달력에 보여줄 이벤트들을 가져옴

class CalendarView(generic.ListView):
    model = class_contents
    template_name = 'cal/calendar.html'
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # 요청에서 날짜 정보 추출
        d = get_date(self.request.GET.get('day', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        
        # 달력과 이전/다음 달 정보를 컨텍스트에 추가
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)

        # EventForm 인스턴스 생성 및 컨텍스트에 추가
        form = EventForm()
        context["form"] = form 

        # 지역(시) 정보를 컨텍스트에 추가
        areas = Area.objects.all()
        area_list = [area.Area for area in areas]
        area_list2 = []
        for area in area_list:
            if area not in area_list2:
                area_list2.append(area)

        context['area_si3'] = area_list2

        # 지역(군,구) 정보를 컨텍스트에 추가
        areas = Area.objects.all()
        context['area_details'] = [area.Area_detail for area in areas]

        return context


# get_daye()는 URL에서 전달된 년도와 월 정보를 추출하여, datatime 객체로 변환하는 함수
# 위에서 선언한 get_context_data() 내에서 호출    
def get_date(req_day):
    try:
        if req_day: 
            year, month, day = (int(x) for x in req_day.split('-'))
            return date(year, month, day=1)
    except (ValueError, TypeError):
        pass
    return datetime.today().date()
# req_day는 URL 매개변수 day의 값을 받아오는 변수
# req_day 값이 존재하면 해당 날짜로부터 date 객체를 생성
# req_day 값이 존재하지 않을 경우 현재 날짜를 사용해 date 객체를 생성

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    a = 'day=' + str(prev_month.year) + '-' + str(prev_month.month) + '-' + str(prev_month.day)
    return a

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    a = 'day=' + str(next_month.year) + '-' + str(next_month.month) + '-' + str(next_month.day)
    return a

serviceKey = "MjYQcO8eIAXD%""2FYqKy8IocJ0HYo4S3%""2FZ4rjNjoz%2B9XaZQvF4j%""2FB8QAhmJqh6mC6dHeMmkCYrg0Pi2xI6OfxMq7A%3D%3D"

def post_detail(request):
    today_W = today_weather.objects.all()
    han = Restaurant.objects.filter(information="한식")
    yang = Restaurant.objects.filter(information="양식")
    joong = Restaurant.objects.filter(information="중식")
    ill = Restaurant.objects.filter(information="일식")
    
    travel = Travel.objects.all()
    today = datetime.now()
    today_date = str("%02d"%(today.month)) + "/" + str("%2d"%(today.day)) + "/" + str("%04d"%(today.year))
    
    post = EventModel.objects.filter(user_id=request.user, edate_s=today_date)
    
    context = {"today_weather" : today_W, "han" : han, "yang" : yang, "joong" : joong, "ill" : ill, "travel" : travel, "post":post, "today_date" : today_date}
    return render(request, 'cal/post_detail.html', context)

def index(request):
    if request.user.is_authenticated:
        return redirect("cal:calendar")
    
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            # username과 password 값을 가져와 변수에 할당
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            # username, password 에 해당하는 사용자가 있는지 검사
            user = authenticate(username=username, password=password)

            # 해당 사용자가 존재한다면
            if user:
                # 로그인 처리 후, 피드페이지로 redirect
                login(request, user)
                return redirect("cal:calendar")
            # 사용자가 없다면 form에 에러 추가
            else: 
                form.add_error(None, "입력한 자격증명에 해당하는 사용자가 없습니다(이걸 틀리네 낄낄)")

        # 실패한 경우 다시 LoginForm 을 사용한 로그 페이지 렌더링
        context = {"form" : form}

    else:
        # LoginForm 인스턴스를 생성
        form = LoginForm()

        # 생성한 LoginForm 인스턴스를 템플릿에 "form" 이라는 키로 전달
        context = {
            "form" : form,
        }
    return render(request, 'cal/index.html', context)

def save_event(request):
    if request.method == 'POST':
        form = EventForm(data=request.POST)
        
        # 로그인 되어있는 유저여야함(추가)
        if form.is_valid():
            event = form.save(commit=False)
            event.user_id = request.user
            event.save()
            return redirect("cal:calendar")  # 성공 페이지로 리다이렉션
    
    return redirect("cal:calendar")


Portfolio/1st_mini_project/templates/cal/base.html
{% load static %}

<!doctype html>
<html lang="ko">
  <head>
    <nav class="navbar">
      <script>
        function showPrompt() {
          // 사용자로부터 입력값 받기
          var inputValue = prompt("시/군/구를 입력하세요:(ex. 서울시 강남구)");
        }
      </script>
    
    <div class="container-fluid">
      <a class="navbar-brand"><h1>Schedule Helper</h1></a>
      <form class="d-flex mt-3" role="search">
        <ul>
          <li id="detailLi" style="display: inline-block;">
            <button id="detail" class="btn btn-primary" type="button"><a href="{% url 'cal:post_detail' %}">상세페이지</a></button>
          </li>
          {% if user.is_authenticated %}
          <li style="display: inline-block; margin-left: 10px;">
            <button onclick="showPrompt()" class="btn btn-primary">선호지역선택</button>
          </li>
          <li id="logoutButtonLi" style="display: inline-block;">
            <button id="logoutButton" class="btn btn-primary" type="button"><a href="{% url 'users:logout' %}">로그아웃</a></button>
            {% else %}
          <li id="loginButtonLi" style="display: inline-block;">
              <button id="loginButton" class="btn btn-primary" type="button"><a href="{% url 'users:login' %}">로그인/회원가입</a></button>
          </li>
          {% endif %}
        </ul>
      </form>
    </div>
    </nav>
    
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- JS -->
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/i18n/datepicker.en.js"></script>
      
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome-font-awesome.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/css/datepicker.css">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
      <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/calendar_style.css' %}"> -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/calendar.css' %}" />
      <title>Schedule Calendar</title>
  </head>
  
  <body>
      {% block content %}
      {% endblock %}


      {% block script %}
      {% endblock %}
      <script src="{% static 'js/calendar.js' %}"></script>
  </body>
</html>

Portfolio/1st_mini_project/templates/cal/calendar.html
{% extends 'cal/base.html' %}
{% load static %}
{% block content %}
<!-- calendar modal -->
<div class="p-5">
  <div class="card">
    <div class="card-body p-0">
      <div id="calendar"></div>
    </div>
  </div>
</div>
{% if user.is_authenticated %}
<div id="modal-view-event-add" class="modal modal-top fade calendar-modal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <form id="add-event"  enctype="multipart/form-data" action="{% url 'cal:calendar' %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          <h4>Add Event Detail</h4>
          <div class="form-group">
            <label>Event name</label>
            <p><input type="text" class="form-control" name="ename"/></p>
            <label>Event Date</label>
            <p><input type="text" class="datetimepicker form-control" name="edate"/></p>
            <label>Event Description</label>
            <p><textarea class="form-control" name="edesc"></textarea></p>
          </div>
          <div class="form-group" method="POST">
            <label>지역(시)</label>
            <select class="form-control" name="지역">
              {% for area_si4 in area_si3 %}
                <option value="{{ area_si4 }}">{{ area_si4 }}</option>
              {% endfor %}
            </select>
          </div>

          <div class="form-group" method="POST">
            <label>지역(군,구)</label>
            <select class="form-control" name="eicon">
              {% for area_detail in area_details %}
                <option value="{{ area_detail }}">{{ area_detail }}</option>
              {% endfor %}
            </select>
          </div>
        </div>

        <div class="modal-footer">
          <p><input type="submit" class="btn btn-primary" value="save"/></p>
          <p><input type="button" class="btn btn-primary" data-dismiss="modal" value="close"/></p>
        </div>
      </form>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}
{% block script %}
{% endblock %}

Portfolio/1st_mini_project/templates/cal/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
    <head>
        <nav class="navbar">
            <div class="container-fluid">
                <a href="{% url 'cal:calendar' %}"><span>Schedule Helper</span></a>
            </div>
        </nav>
        <link rel="stylesheet" href="https://fonts.googleapis.com/earlyaccess/notosanskr.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
        <title>Schedule Helper</title>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/CSSRulePlugin.min.js"></script>
        <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/Physics2DPlugin3.min.js"></script>
        <script>
            gsap.registerPlugin(Physics2DPlugin);
        </script>
    </head>

    <body class="pt-5">
        <div class="container" onclick="onclick">
            <div class="top"></div>
            <div class="bottom"></div>
            <div class="center">
                <form method="POST">
                {% csrf_token %}
                <center>
                <h2>Schedule로 들어가기🚀</h2>
                </center>
                {% for i in form %}
                    {{ i }}
                {% endfor %}
                <center>
                <button type="submit" class="button white" style="--rx: 0; --ry: 0;">
                    <div class="icon">
                        <div class="cannon"></div>
                        <div class="confetti">
                            <svg viewBox="0 0 18 16">
                                <polyline points="1 10 4 7 4 5 6 1" />
                                <path d="M4,13 C5.33333333,9 7,7 9,7 C11,7 12.3340042,6 13.0020125,4"></path>
                                <path d="M6,15 C7.83362334,13.6666667 9.83362334,12.6666667 12,12 C14.1663767,11.3333333 15.8330433,9.66666667 17,7"></path>
                            </svg>
                            <i></i><i></i><i></i><i></i><i></i><i></i>
                            <div class="emitter"></div>
                        </div>
                    </div>
                    로그인
                </button>
                <script src="{% static 'js/index.js' %}"></script>
                <div class="text">
                    <a href="{% url 'cal:calendar' %}">
                        <p>비회원 이용하기</p>
                    </a>
                </div>
               </center>
            </div>
        </div>
    </body>
</html>

Portfolio/1st_mini_project/templates/cal/post_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Schedule Helper</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}" />
    </head>

    <body>
        <main class="dashboard">
            <nav class="dashboard-sidenav">
              <h2><a href="{% url 'cal:calendar' %}" class="logo" >Schedule Helper</a></h2>
            </nav>

            <article class="dashboard-content">
                <header class="welcome-banner">
                  {% for i in post %}
                    <h1>일정명 : {{ i.ename }}</h1>
                    <h2>Today : {{ i.edate_s }}</h2>
                    <h3><strong>일정내용 : {{i.edesc}}</strong></h3>
                  {% empty %}
                    <h1>일정이 없습니다</h1>
                    <h2>Today : {{ today_date }}</h2>
                  {% endfor %}
                </header>

                <section class="section">
                    <div class="section-titles"></div>
                    <ul class="monitor-list">
                        <li class="monitor-list__item">
                            <div class="monitor-data">
                                <div class="monitor-type"><strong>🧥 오늘의 코디</strong></div>
                            </div>
                            <div class="monitor-gauge">
                                (옷차림 추천)</a>
                            </div>
                        </li>
                        
                        <li class="monitor-list__item active">
                            <div class="monitor-data2">
                              <div class="monitor-type"><strong>🎵 Today's music</strong></div>
                            </div>
                            <div class="monitor-gauge">
                            </div>
                        </li>
                    </ul>
                </section>
                
                <section class="section">
                    <div class="section-titles"></div>
                      <div class="main__cards">
                        <div class="card">
                          <div class="card__header">
                            <div class="card__header-title text-light"><strong>☀️ 오늘의 날씨 ☀️</strong></div>
                          </div>
    
                          <div class="card__main">
    
                            {% for i in today_weather %}
                                <div class="card__row">
                                    <div class="card__icon"><i class="fas fa-heart"></i></div>
                                    <div class="card__time">
                                        <div></div>
                                    </div>
                                    <div class="card__detail">
                                        <div class="card__description">{{i.information}}</div>
                                        <div class="card__note">{{i.value}}</div>
                                    </div>
                                </div>
                            {% endfor %}
                            </div>
                        </div>
                      </div>
                    </div>
                  </section>                
                </article>

            <article class="dashboard-others">
                <section class="section">
                    <h2>⭐ 추천 리스트</h2>
                    <div class="section-titles">
                        <div class="section-title">🍽️ 맛집 추천</div>
                    </div>
                    <ul class="function-list">
                      <li class="function-list__item" style="--function-color: var(--first==-cate-color);">
                        <div class="function">
                          <div class="function">
                            <div class="text"><p><strong>한 식</strong></p></div>
                          </div>
                        </div>
                        <div>
                          {% for i in han %}
                          <p style="font-size:12px">{{i.rank}}. {{i.title}}</p>
                          {% endfor %}
                        </div>
                      </li>
                      <li class="function-list__item" style="--function-color: var(--second-cate-color);">
                          <div class="function">
                              <div class="function">
                                <div class="text"><p><strong>양 식</strong></p></div>
                              </div>
                          </div>
                          <div>
                            {% for i in yang %}
                            <p style="font-size:12px">{{i.rank}}. {{i.title}}</p>
                            {% endfor %}
                          </div>
                      </li>
                      <li class="function-list__item" style="--function-color: var(--third-cate-color);">
                        <div class="function">
                          <div class="function">
                            <div class="text"><p><strong>중 식</strong></p></div>
                          </div>
                        </div>
                        <div>
                        {% for i in joong %}
                         <p style="font-size:12px">{{i.rank}}. {{i.title}}</p>
                        {% endfor %}
                        </div>
                      </li>
                      <li class="function-list__item" style="--function-color: var(--fourth-cate-color);">
                        <div class="function">
                          <div class="function">
                            <div class="text"><p><strong>일 식</strong></p></div>
                          </div>
                        </div>
                        <div>
                        {% for i in ill %}
                          <p style="font-size:12px">{{i.rank}}. {{i.title}}</p>
                        {% endfor %}
                        </div>
                        <div class="function-data">
                          <div class="function-name"></div>
                        </div>
                      </li>
                    </ul>
                </section>

                <section class="section">
                    <div class="section-titles">
                        <div class="section-title">
                            ✈️ 여행지 추천
                        </div>
                    </div>
                    <div class="statistics">
                        <div class="progress-data">
                            <div class="progress-text">
                              {% for i in travel %}
                              <div class="progress-weekday" style="font-size:20px;"><strong>{{i.rank}}. {{ i.title }}</strong></div>
                              <div class="progress-weekday" style="font-size:15px;">{{ i.address }}</div>
                              {% endfor %}
                            </div>
                        </div>
                    </div>
                </section>
            </article>
        </main>
        <script src="{% static 'js/detial.js' %}"></script>
    </body>
</html>