4. web/web_project5/posts/urls.py
from django.urls import path
from posts import views

app_name = "posts"
urlpatterns = [
    path("feeds/", views.feeds, name="feeds"),
    path("comment_add/", views.comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", views.comment_delete, name="comment_delete"),
    path("post_add/", views.post_add, name="post_add"),
    path("tags/<str:tag_name>/", views.tags, name="tags"), 
    path("<int:post_id>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/like/", views.post_like, name="post_like"),
]

4. web/web_project5/pystagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from pystagram import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
]
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

4. web/web_project5/users/urls.py
from django.urls import path
from users import views

app_name = "users"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"), 
    path("signup/", views.signup, name="signup"),
    path("<int:user_id>/profile/", views.profile, name="profile"),
    path("<int:user_id>/followers/", views.followers, name="followers"),
    path("<int:user_id>/following/", views.following, name="following"),
    path("<int:user_id>/follow/", views.follow, name="follow"),
]

4. web/web_project5/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey("users.User", 
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    content = models.TextField("내용", blank=True)           # 얘만 내가 고르는거임
    created = models.DateTimeField("작성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag", verbose_name="해시태그 목록", blank=True)    # 그냥 HashTag 하면 인식 안 됨 밑에 있어서 그래서 posts.HashTag
    
    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"

class PostImage(models.Model):
    post = models.ForeignKey(Post,
                             verbose_name="포스트",
                             on_delete=models.CASCADE)
    photo = models.ImageField("사진", upload_to="post")

class Comment(models.Model):
    user = models.ForeignKey("users.User",
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    post = models.ForeignKey(Post,
                             verbose_name="포스트",
                             on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add=True)

class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

4. web/web_project5/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <link rel="stylesheet" href="{% static 'css/pystagram_style.css' %}">
        <title>Pystagram</title> <!-- 크롬 상단에 뜰 내용 -->
        {% block head %}{% endblock %}
    </head>
    <body>
        {% block base_content %}{% endblock %}
    </body>
</html>

4. web/web_project5/templates/base_nav.html
{%extends '_base.html' %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
{% endblock %}

4. web/web_project5/templates/base_profile.html
{% extends 'base_nav.html' %}

{% block content %}
<div id="profile">
        <div class="info">
            <!-- 프로필 이미지 영역 -->
            {% if user.profile_image %}
                <img src="{{ user.profile_image.url }}">
            {% endif %}

            <!-- 사용자 정보 영역 -->
            <div class="info-texts">
                <h1>{{ user.username }}</h1>
                <div class="counts">
                    <dl>
                        <dt>Posts</dt>
                        <dd>{{ user.post_set.count }}</dd>
                        <dt>Followers</dt>
                        <dd>{{ user.followers.count}}</dd>
                        <dt>Following</dt>
                        <dd>{{ user.following.count }}</dd>
                    </dl>
                </div>
                <p>{{ user.short_description }}</p>
            </div>
        </div>
    {% block bottom_data %}{% endblock %}
</div>
{% endblock %}

4. web/web_project5/templates/base_slider.html
{% extends '_base.html' %}
{% load static %}

{% block head%}
    <link href="{% static 'splide/splide.css' %}" rel="stylesheet">
    <script src="{% static 'splide/splide.js' %}"></script>
{% endblock %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
    <script>
        const elms = document.getElementsByClassName("splide")
        for (let i = 0; i < elms.length; i++) {
            new Splide(elms[i]).mount();
        }
    </script>
{% endblock %}

4. web/web_project5/templates/nav.html
<nav>
    <h1>
        <a href="{% url 'posts:feeds' %}">Pystagram</a>
    </h1>
    <a href="{% url 'posts:post_add' %}">Add post</a>
    <a href="{% url 'users:logout' %}">Logout</a>
</nav>